import '../styles/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
export function initMap() {
    // Seu código para inicializar o mapa vai aqui
}
export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <>
            <head>
                <script
                    async
                    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC9kWuM0oCoy6PsyhIsykG3XNRNZ2HIoe4&libraries=places&callback=initMap"
                ></script>
            </head>
            <html lang="en">
                <body>{children}</body>
            </html>
        </>
    )
}
